scoped_search.gemspec

I was trying to determine the licenses for my dependencies. I found that the RubyGems API will return the license, but only if it is specified in your gemspec file.

Add license to gemspec

---

lib/scoped_search/auto_complete_builder.rb
spec/integration/auto_complete_spec.rb

Fix auto completer for in on PostgreSQL by using the Cast function to cast int to char before using the like operator. and updated the test to verify the new functionality.

fixed integer value auto completer

---

lib/scoped_search/definition.rb
spec/integration/string_querying_spec.rb

ScopedSearch::Definition#register_named_scope! can return a bare model class when used with ActiveRecord 4.x if ScopedSearch::QueryBuilder returns no find_options.
Under AR 3.x it returns @klass.scoped, in AR 4.x that should by @klass.all or (due a bug in AR 4.0) @klass.where(nil)
Note that this can create a serious security issue. E.g:
[1] pry(main)> Invoice.count
=> 148
[2] pry(main)> Company.first.invoices.count
=> 20
[3] pry(main)> Company.first.invoices.search_for('').count
=> 148

Make sure search_for always return an AR Relation

---

lib/scoped_search/auto_complete_builder.rb
spec/integration/auto_complete_spec.rb

prior to this change auto-completing any attribute that existed on the same
table as the class would fail if the query already had 'distinct' applied.
The resulting query would have distinct twice, as seen by the added integration test run on master:
Failure/Error: Foo.uniq.complete_for('int =').length.should > 0
ActiveRecord::StatementInvalid:
PG::SyntaxError: ERROR:  syntax error at or near "DISTINCT"
LINE 1: SELECT  DISTINCT DISTINCT "foos"."int" FROM "foos"  ORDER BY...
^
: SELECT  DISTINCT DISTINCT "foos"."int" FROM "foos"  ORDER BY "foos"."int" LIMIT 20

use active record "uniq" to apply distinct for auto-complete

---

lib/scoped_search/rails_helper.rb
spec/unit/rails_helper_spec.rb

sort() previously showed an arrow pointing up when the current sort
order was descending, and vice versa.  Changed from showing the style
for the linked, future order to the current order.

Show correct styling for current sort order

---

lib/scoped_search/auto_complete_builder.rb
spec/integration/key_value_querying_spec.rb

Previously either a field or a quoted field string was passed into
value_conditions, causing the following error when expanding
auto-complete values for partial keys:
NoMethodError:
undefined method `quoted_field' for "\"keys\".\"name\"":String

Fix auto-completion of partial key name in key/value configurations

---

lib/scoped_search/auto_complete_builder.rb
spec/integration/auto_complete_spec.rb

otherwise large lists of non-uniq values can prevent
other values from appearing in auto complete

apply auto complete distinct before limit

---

lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

Instead of requiring the use of the default Rails PostgreSQL adapter
to make use of Postgres-specific scoped searches, try to guess if
the connection is PG based on the connection class name.

Fixes issue #139

---

.travis.yml
Gemfile.activerecord50
lib/scoped_search/definition.rb

I was getting the following running:
Rails 5.0.0.beta3
scoped_search 3.2.2
Ruby 2.3.0
MySQL 5.6.19
```
NoMethodError - undefined method `where' for nil:NilClass:
scoped_search (3.2.2) lib/scoped_search/definition.rb:253:in `block in register_named_scope!'
activerecord (5.0.0.beta3) lib/active_record/scoping/named.rb:159:in `block (2 levels) in scope'
activerecord (5.0.0.beta3) lib/active_record/relation.rb:351:in `scoping'
activerecord (5.0.0.beta3) lib/active_record/scoping/named.rb:159:in `block in scope'
activerecord (5.0.0.beta3) lib/active_record/relation/delegation.rb:89:in `block in method_missing'
activerecord (5.0.0.beta3) lib/active_record/relation.rb:351:in `scoping'
activerecord (5.0.0.beta3) lib/active_record/relation/delegation.rb:89:in `method_missing' …
```

Fix Definition#register_named_scope! for Rails 5

---

lib/scoped_search/auto_complete_builder.rb

uniq is deprecated in Rails 5.0, and will be removed in 5.1.

Prefer distinct over uniq on AR scopes on Rails 4+

---

spec/unit/ast_spec.rb

Fixes a warning issued by rspec that the exception class and/or message
is not given.

Specify classes/messages for raise_error matcher

---

lib/scoped_search/rails_helper.rb
spec/unit/rails_helper_spec.rb

On Rails 5, passing `params` directly into `url_for` results in:
ActionView::Template::Error (Attempting to generate a URL from
non-sanitized request parameters! An attacker can inject malicious
data into the generated URL, such as changing the host. Whitelist
and sanitize passed parameters to be secure.):
The url_options/params is now parameterised so the user can pass a
filtered list of current URL options to the helper. If the default
`params` is used or an AC::Parameters object is passed, it's converted
to a hash of filtered parameters.

Filter URL parameters from ActionController::Parameters in sort helper

---

.travis.yml
Gemfile.activerecord32
Gemfile.activerecord40
Gemfile.activerecord41
Gemfile.activerecord42
Gemfile.activerecord50

Also matches the gem versions expected by ActiveRecord adapters (`grep ^gem lib/active_record/connection_adapters/*.rb`), including the newer, supported mysql2 0.4 series in newer AR versions.

Remove Ruby 1.9 from test matrix

---

lib/scoped_search/query_builder.rb
spec/integration/relation_querying_spec.rb

as a reproducer, you can use Foreman and it's issue described in http://projects.theforeman.org/issues/17364
in general, condition that's being searched is being searched in wrong reflection. If the condition from this different reflection defines some condition on its column e.g. type (polymorphic association on its type) it adds this field to resulting WHERE but the column does not exist anywhere in the relation.

Fixes wrong association on through conditions

---

lib/scoped_search/definition.rb
spec/unit/definition_spec.rb

I've added deprecations and workarounds for `:in` and `:alias` because they're the names of reserved words in Ruby. Improvements to the suggested replacements of `:relation` and `:aliases` welcome. Alternatively I can leave them undeprecated, but it'd be cleaner if they didn't exist.

Convert Definition::Field.new to keyword arguments

---

lib/scoped_search/rails_helper.rb
spec/unit/rails_helper_spec.rb

The documented `:by` option doesn't seem to exist, it's actually the first position argument.

Convert sort() Rails helper to keyword arguments

---

spec/integration/auto_complete_spec.rb
spec/integration/key_value_querying_spec.rb
spec/integration/relation_querying_spec.rb
spec/integration/string_querying_spec.rb

Forgot to do these, sorry. It fixes lots of deprecation warnings running `rake spec`.

Fix specs to use preferred :relation/:aliases options in definitions

---

lib/scoped_search/auto_complete_builder.rb
lib/scoped_search/definition.rb
spec/integration/ordinal_querying_spec.rb

Date fields can now be searched using future relative time phrases, such
as 'tomorrow', '2 weeks from now' and so on.

Fixes #162 - Allow searching by future relative dates

---

Gemfile
Gemfile.activerecord42
Gemfile.activerecord50
Gemfile.activerecord51
lib/scoped_search/rails_helper.rb
spec/integration/rails_helper_spec.rb

The private `tag_options` method was refactored away in
rails/rails@a65a3bd. Adds ActionView to spec to make all HTML-safe
extensions available.

Replace private tag_options call with public content_tag helper

---

CHANGELOG.rdoc
lib/scoped_search.rb
lib/scoped_search/definition.rb
spec/integration/api_spec.rb
spec/integration/scope_spec.rb
spec/integration/sti_querying_spec.rb
spec/lib/database.rb
spec/lib/mocks.rb
spec/unit/definition_spec.rb

Two distinct fixes to add Single Table Inheritance (STI) support:
---
**Use current class from scope when searching, not the definition class**
With an STI parent and subclass, calling `Parent.where` within a named
scope (i.e. `search_for`) in Rails 5+ now correctly returns all parent
and subclass records. When calling `Subclass.search_for`, this would
return unexpected results from other subclasses.
Querying the class that the scope was called on ensures the result is
limited to that class, restoring very basic STI support.
Fixes #112
---
**Definitions inherit fields from STI parent class too**
When `scoped_search` is called on a parent and then its subclass, a new
`Definition` will be created and stored on the subclass that inherits
and merges fields with its parent.
The named scope …

STI support: searching on subclasses, parent definition inheritance

---

Gemfile.activerecord51
lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

The problem is when you specify e.g. numeric validator and the do something like
`Model.search_for("numeric_param ^ (1,2)")`, it validates the whole value. For :in operator we need to split the value by comma and validate each one separately.

Fix validations on :in operator

---

lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

Currently, if an ext_method raises an error, it is silently captured and
the query is executed with no conditions. This PR will change it so that
and such exception is caught and an informative error is raised.

Don't swallow errors in external methods

---

CHANGELOG.rdoc
lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

Reviving #172 
This allows LIKE queries to work on definitions with ext_method but no corresponding database column.

Don't check column type when ext_method

---

lib/scoped_search/auto_complete_builder.rb
lib/scoped_search/definition.rb
lib/scoped_search/query_builder.rb
spec/unit/auto_complete_builder_spec.rb
spec/unit/query_builder_spec.rb

Before this patch scoped_search allowed to define value mappings using the
complete_value, but these mappings were static. This patch introduces dynamic
value mapping which is resolved at search time, instead of at definition time.
This allows us to do searches like
```ruby
scoped_search on: :id,
value_translation: ->(value) { value == 'current' ? User.current.id : value },
validator: ->(value) { value =~ /\d+/ || value == 'current' },
special_values: %w(current)
```
Please note the validations are run on the not yet translated input as provided
by the user.

Allow value mapping at search time

---

lib/scoped_search/definition.rb
spec/integration/key_value_querying_spec.rb

With definition like:
```ruby
scoped_search :on => :a,
:rename => 'something'
scoped_search :on => :b,
:rename => 'something.else'
```
Searching for query like `something.custom_key = 5` would search on the `b` column for value `5`.

Don't allow matching by first part of key before dot

---

lib/scoped_search/auto_complete_builder.rb
spec/integration/auto_complete_spec.rb

Example usage:
```ruby
@items = model.complete_for(params[:search], value_filter: {user_id: current_user.id})
```
In this particular app all records belong to a user and so this would allow limiting auto complete values to the values that belong to a user.

Support extra filter on auto complete value

---

lib/scoped_search/auto_complete_builder.rb
lib/scoped_search/definition.rb

These are marked as "dangerous SQL" since Rails 5.2 and will fail with
Rails 6.1.

Wrap order clauses in Arel.sql()

---

.travis.yml
lib/scoped_search/definition.rb

This addresses the only issue I could find running tests under ruby 3.0.0.
A few tests fails when running under `Gemfile` but that seems to be due to an error with rails 6.1 and habtm joins. The same tests fails under ruby 2.7.2
Using `Gemfile.activerecord60_with_activesupport60` all tests runs under ruby 3.0.0 after this fix.
Closes #203

Support ruby 3.0.0

---

CHANGELOG.rdoc
lib/scoped_search/query_builder.rb

reflection.join_keys is no longer available. Extract the
join_primary_key and join_foreign_key explicitly.
Using the workaround provided by @stevequinlan this fixes the 57 test failures mentioned in #201.

Fix search through relations in Rails 6.1 (undefined method join_keys)

---

lib/scoped_search/definition.rb
spec/integration/ordinal_querying_spec.rb
spec/integration/rails_helper_spec.rb

Previously queries like 'yesterday' would resolve to only a specific
date, discarding any information about the user's time zone. After this
change, `datetime` and `timestamp` fields take the time zone into
consideration.

Honor TZ when searching on temporal fields by relative dates

---

lib/scoped_search/query_builder.rb
spec/integration/set_query_spec.rb

Without this change we were running into errors like this:
```
ActiveRecord::PreparedStatementInvalid:
wrong number of bind variables (0 for 1) in: (("model_0018166730307353163"."bool" <> ?))
```

Fix searching on set values when only the key is provided

---

lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

This commit fixes the following error
Model.search_for("id !^ (2,3)") fails with
ScopedSearch::QueryNotSupported: Value '2,3' is not valid for field 'id'
It does it by splitting value for both in and not in

Validate both in and notin the same way

---

lib/scoped_search/query_language/parser.rb
spec/unit/parser_spec.rb

Previously, searching for things like `& thing` constructed the AST incorrectly. Parsing `& thing` would produce the AST which would simplify into `<AST::OperatorNode [:and, "thing"]>`, which then couldn't really be used for searching.
This change builds the AST fully, meaning this will accept even things like `& & & & & & thing` which will then simplify into a single LeafNode.

Allow use of logical operators with single arg

---

lib/scoped_search/query_builder.rb
spec/unit/query_builder_spec.rb

The current implementation causes issues such as:
1. When searching for timestamps greater than the given value and
minutes and seconds are omitted the value, it returns only timestamps
greater than value + 1 hour.
2. When searching for timestamps greater than the given value and only
month is provided as the smallest time unit, it excludes only timestamps
from the first day of the month in the results but includes rest of
month. Based on the logic implemented here this should not happen but
instead the whole month should be excluded from the search results, i.e.
'> January 2024' should exclude all January timestamps.
Same problems occur when searching with `<=`.
This PR aims to fix these issues.

Improve search queries based on datetime

---

CHANGELOG.rdoc
lib/scoped_search/auto_complete_builder.rb
spec/integration/auto_complete_spec.rb

This change modifies AutoCompleteBuilder's `complete_value_from_db` method. 
Previously, DB values that were strings would automatically be wrapped in quotes if the values contained spaces.
Now, DB values that are strings are wrapped in quotes, regardless of contents.
This is so that special operators ('|', '>', etc) don't break queries. For a more detailed explanation of the issue, see https://github.com/theforeman/foreman_rh_cloud/pull/1083.

Wrap all string autocomplete values in quotes, not just those containing whitespace

---

lib/scoped_search/definition.rb
spec/integration/uuid_query_spec.rb

When searching for a UUID, input should be accepted independent of case because
[RFC 4122 Section 3](https://datatracker.ietf.org/doc/html/rfc4122#section-3) states:
```
The hexadecimal values "a" through "f" are output as
lower case characters and are case insensitive on input.
```

Make UUID search case insensitive
